# Brewfile — Martin Pritchard
# Generated by: brew bundle dump --file=~/dotfiles/Brewfile --force
#
# Install everything:
#   brew bundle install --file=~/dotfiles/Brewfile
#
# Keep up to date:
#   brew bundle dump --file=~/dotfiles/Brewfile --force  (regenerate from current state)
#   brew bundle cleanup --file=~/dotfiles/Brewfile       (remove anything not in this file)

# ── CLI tools ───────────────────────────────────────────────
brew "chezmoi"                # Dotfiles manager (this repo!)
brew "bat"                    # Better cat (syntax highlighting)
brew "eza"                    # Better ls (with icons, git status)
brew "fd"                     # Better find
brew "fnm"                    # Fast Node Manager
brew "fzf"                    # Fuzzy finder (Ctrl+R etc.)
brew "gh"                     # GitHub CLI
brew "git-delta"              # Better git diff output
brew "ripgrep"                # Better grep (rg)
brew "starship"               # Cross-shell prompt
brew "zoxide"                 # Smart cd (z)
brew "zsh-autosuggestions"    # Fish-style suggestions in zsh
brew "zsh-syntax-highlighting" # Syntax highlighting in zsh

# ── Fonts ────────────────────────────────────────────────────
cask "font-jetbrains-mono-nerd-font"   # Used in Ghostty

# ── Terminal ─────────────────────────────────────────────────
cask "ghostty"

# ── 1Password CLI ────────────────────────────────────────────
cask "1password-cli"          # op — sign into 1Password account to activate

# ── VS Code extensions ───────────────────────────────────────
# (brew bundle installs these automatically if VS Code is already installed)
vscode "anthropic.claude-code"
vscode "vscode-icons-team.vscode-icons"

# ── GUI Apps ─────────────────────────────────────────────────
cask "raycast"
cask "1password"
cask "visual-studio-code"
cask "cursor"
cask "zed"
cask "google-chrome"

# ── bun (not via Homebrew) ───────────────────────────────────
# bun was installed via its own installer, not brew.
# On a new Mac, install it with:
#   curl -fsSL https://bun.sh/install | bash
