#!/usr/bin/env bash
# capture-macos-defaults.sh
# Run this on your CURRENT Mac to read your actual settings.
# Paste the output back so we can build macos.sh from your real preferences.
#
# Usage: bash ~/dotfiles/scripts/capture-macos-defaults.sh

echo "====== DOCK ======"
defaults read com.apple.dock tilesize 2>/dev/null | xargs echo "tilesize:"
defaults read com.apple.dock autohide 2>/dev/null | xargs echo "autohide:"
defaults read com.apple.dock orientation 2>/dev/null | xargs echo "orientation:"
defaults read com.apple.dock show-recents 2>/dev/null | xargs echo "show-recents:"
defaults read com.apple.dock magnification 2>/dev/null | xargs echo "magnification:"
defaults read com.apple.dock mineffect 2>/dev/null | xargs echo "mineffect:"
defaults read com.apple.dock minimize-to-application 2>/dev/null | xargs echo "minimize-to-application:"
defaults read com.apple.dock launchanim 2>/dev/null | xargs echo "launchanim:"
defaults read com.apple.dock autohide-delay 2>/dev/null | xargs echo "autohide-delay:"
defaults read com.apple.dock autohide-time-modifier 2>/dev/null | xargs echo "autohide-time-modifier:"
defaults read com.apple.dock expose-animation-duration 2>/dev/null | xargs echo "expose-animation-duration:"
defaults read com.apple.dock mru-spaces 2>/dev/null | xargs echo "mru-spaces:"

echo ""
echo "====== FINDER ======"
defaults read com.apple.finder AppleShowAllFiles 2>/dev/null | xargs echo "show-hidden-files:"
defaults read com.apple.finder ShowPathbar 2>/dev/null | xargs echo "path-bar:"
defaults read com.apple.finder ShowStatusBar 2>/dev/null | xargs echo "status-bar:"
defaults read com.apple.finder FXPreferredViewStyle 2>/dev/null | xargs echo "view-style (Nlsv=list, icnv=icon, clmv=column, Flwv=gallery):"
defaults read com.apple.finder FXDefaultSearchScope 2>/dev/null | xargs echo "search-scope (SCcf=current folder, SCev=everywhere):"
defaults read com.apple.finder NewWindowTarget 2>/dev/null | xargs echo "new-window-target:"
defaults read com.apple.finder _FXShowPosixPathInTitle 2>/dev/null | xargs echo "show-full-path-in-title:"
defaults read com.apple.finder FXEnableExtensionChangeWarning 2>/dev/null | xargs echo "extension-change-warning:"
defaults read NSGlobalDomain AppleShowAllExtensions 2>/dev/null | xargs echo "show-all-extensions:"
defaults read com.apple.finder QuitMenuItem 2>/dev/null | xargs echo "quit-menu-item:"

echo ""
echo "====== SCREENSHOTS ======"
defaults read com.apple.screencapture location 2>/dev/null | xargs echo "location:"
defaults read com.apple.screencapture type 2>/dev/null | xargs echo "type:"
defaults read com.apple.screencapture disable-shadow 2>/dev/null | xargs echo "disable-shadow:"
defaults read com.apple.screencapture include-date 2>/dev/null | xargs echo "include-date:"

echo ""
echo "====== KEYBOARD ======"
defaults read NSGlobalDomain KeyRepeat 2>/dev/null | xargs echo "key-repeat (lower=faster, 2=fast):"
defaults read NSGlobalDomain InitialKeyRepeat 2>/dev/null | xargs echo "initial-key-repeat (lower=faster, 15=fast):"
defaults read NSGlobalDomain ApplePressAndHoldEnabled 2>/dev/null | xargs echo "press-and-hold (false=key repeat enabled):"
defaults read NSGlobalDomain NSAutomaticSpellingCorrectionEnabled 2>/dev/null | xargs echo "auto-correct:"
defaults read NSGlobalDomain NSAutomaticCapitalizationEnabled 2>/dev/null | xargs echo "auto-capitalise:"
defaults read NSGlobalDomain NSAutomaticDashSubstitutionEnabled 2>/dev/null | xargs echo "smart-dashes:"
defaults read NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled 2>/dev/null | xargs echo "smart-quotes:"
defaults read NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled 2>/dev/null | xargs echo "period-on-double-space:"

echo ""
echo "====== TRACKPAD ======"
defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking 2>/dev/null | xargs echo "tap-to-click:"
defaults read NSGlobalDomain com.apple.trackpad.scaling 2>/dev/null | xargs echo "tracking-speed:"
defaults read NSGlobalDomain com.apple.swipescrolldirection 2>/dev/null | xargs echo "natural-scrolling:"

echo ""
echo "====== MENU BAR / UI ======"
defaults read NSGlobalDomain AppleInterfaceStyle 2>/dev/null | xargs echo "interface-style (Dark or not set=Light):"
defaults read NSGlobalDomain AppleInterfaceStyleSwitchesAutomatically 2>/dev/null | xargs echo "auto-dark-mode:"
defaults read NSGlobalDomain AppleHighlightColor 2>/dev/null | xargs echo "highlight-color:"
defaults read com.apple.menuextra.battery ShowPercent 2>/dev/null | xargs echo "battery-percentage:"
defaults read NSGlobalDomain NSWindowResizeTime 2>/dev/null | xargs echo "window-resize-time (lower=faster):"

echo ""
echo "====== MISSION CONTROL ======"
defaults read com.apple.dock mru-spaces 2>/dev/null | xargs echo "rearrange-spaces-automatically:"
defaults read com.apple.spaces spans-displays 2>/dev/null | xargs echo "displays-have-separate-spaces:"

echo ""
echo "====== SAFARI (dev tools) ======"
defaults read com.apple.Safari IncludeDevelopMenu 2>/dev/null | xargs echo "develop-menu:"

echo ""
echo "====== MISC ======"
defaults read NSGlobalDomain NSDocumentSaveNewDocumentsToCloud 2>/dev/null | xargs echo "save-to-icloud-by-default:"
defaults read com.apple.LaunchServices LSQuarantine 2>/dev/null | xargs echo "gatekeeper-quarantine:"
defaults read NSGlobalDomain PMPrintingExpandedStateForPrint 2>/dev/null | xargs echo "expanded-print-dialog:"
